# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/item_action.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemAction(object):
    """Интерфейс для создания/редактирования записи"""
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 213)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.title = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setText("")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")

        self.verticalLayout.addWidget(self.title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.name_line = QtWidgets.QLineEdit(Form)
        self.name_line.setObjectName("name_line")
        self.horizontalLayout_2.addWidget(self.name_line)
        self.name_line.setMaxLength(20)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.name_line.setFont(font)

        self.category_line = QtWidgets.QLineEdit(Form)
        self.category_line.setObjectName("category_line")
        self.horizontalLayout_2.addWidget(self.category_line)
        self.category_line.setMaxLength(20)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.category_line.setFont(font)

        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.about_line = QtWidgets.QTextEdit(Form)
        self.about_line.setObjectName("about_line")
        self.verticalLayout_3.addWidget(self.about_line)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.about_line.setFont(font)

        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 15)

        self.label_1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        self.label_1.setFont(font)
        self.label_1.setText("Цена")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_4.addWidget(self.label_1)

        self.price_line = QtWidgets.QDoubleSpinBox(Form)
        self.price_line.setObjectName("price_line")
        self.verticalLayout_4.addWidget(self.price_line)
        self.price_line.setMinimum(0.5)
        self.price_line.setMaximum(10 ** 10)
        self.price_line.setSingleStep(0.5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.price_line.setFont(font)

        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setText("Дата покупки")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_4.addWidget(self.label_2)

        self.date_line = QtWidgets.QDateEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_line.sizePolicy().hasHeightForWidth())
        self.date_line.setSizePolicy(sizePolicy)
        self.date_line.setObjectName("date_line")
        self.verticalLayout_4.addWidget(self.date_line)
        self.date_line.setMinimumDate(datetime.date(2022, 1, 1))
        self.date_line.setMaximumDate(datetime.date.today())
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.date_line.setFont(font)

        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.buttonBox.setFont(font)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_line.setText(_translate("Form", "Введите название"))
        self.category_line.setText(_translate("Form", "Введите категорию"))
        self.about_line.setText(_translate("Form", "Введите описание покупки"))
